module.exports = {
    status: {
        OK: 0,
        CANCELLED: 1,
        UNKNOWN: 2,
        INVALID_ARGUMENT: 3,
        DEADLINE_EXCEEDED: 4,
        NOT_FOUND: 5,
        ALREADY_EXISTS: 6,
        PERMISSION_DENIED: 7,
        RESOURCE_EXHAUSTED: 8,
        FAILED_PRECONDITION: 9,
        ABORTED: 10,
        OUT_OF_RANGE: 11,
        UNIMPLEMENTED: 12,
        INTERNAL: 13,
        UNAVAILABLE: 14,
        DATA_LOSS: 15,
        UNAUTHENTICATED: 16,
    },
    credentials: {
        createInsecure: jest.fn(),
        createSsl: jest.fn(),
        combineChannelCredentials: jest.fn(),
        combineCallCredentials: jest.fn(),
    },
    loadPackageDefinition: jest.fn(),
    Server: jest.fn().mockImplementation(() => ({
        addService: jest.fn(),
        bind: jest.fn(),
        start: jest.fn(),
        tryShutdown: jest.fn(),
        forceShutdown: jest.fn(),
    })),
    ServerCredentials: {
        createInsecure: jest.fn(),
        createSsl: jest.fn(),
    },
    Metadata: jest.fn().mockImplementation(() => ({
        add: jest.fn(),
        set: jest.fn(),
        get: jest.fn(),
        remove: jest.fn(),
        clone: jest.fn(),
    })),
    ClientReadableStream: jest.fn(),
    ClientWritableStream: jest.fn(),
    ClientDuplexStream: jest.fn(),
    sendUnaryData: jest.fn(),
};
