# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: addtocart
# "service" is the name of this project. This will also be added to your AWS resource names.
service: atc-admin-notification

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: ap-south-1
  memorySize: 256 # Optional: Set memory for Lambda
  timeout: 900
  environment:
    DEV_DATABASE_URL: ${env:DEV_DATABASE_URL}
    SECRET_ACCESS_KEY: ${env:SECRET_ACCESS_KEY}
    ACCESS_KEY_ID: ${env:ACCESS_KEY_ID}
    REGION: ${env:REGION}
    SIB_HOST: ${env:SIB_HOST}
    SIB_USER: ${env:SIB_USER}
    SIB_PASS: ${env:SIB_PASS}
    SIB_SENDER_EMAIL: ${env:SIB_SENDER_EMAIL}

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: "*"

plugins:
  - serverless-offline
