// Auto-generated mock file for @atc/common
module.exports = {
  errorMessage: {
    DATE: {
      DATE_BEFORE_START: 'Date Before Start',
      INVALID_DATE: 'Invalid Date',
      PAST_DATE: 'Past Date',
    },
    OTHER: {
      FILL_REQUIRED_FIELD: 'Fill Required Field',
      SOMETHING_WENT_WRONG: 'Something Went Wrong',
    },
    SURVEY: {
      ALREADY_EXISTS: 'Already Exists',
      ALREADY_SUBMITTED_ANSWER: 'Already Submitted Answer',
      CANNOT_ADD_OPTION: 'Cannot Add Option',
      CANNOT_UPDATE_PUBLISHED: 'Cannot Update Published',
      DEACTIVATE: 'Deactivate',
      DRAFT_NOT_FOUND: 'Draft Not Found',
      FAILED_SUBMIT_ANSWER: 'Failed Submit Answer',
      FAILED_TO_CREATE: 'Failed To Create',
      FAILED_TO_DELETE: 'Failed To Delete',
      FAILED_TO_UPDATE: 'Failed To Update',
      INVALID_AGE: 'Invalid Age',
      INVALID_LOCATION: 'Invalid Location',
      INVALID_STATE: 'Invalid State',
      MAXIMUM_TARGET_AUDIENCE: 'Maximum Target Audience',
      MAX_CLIENT_LENGTH: 'Max Client Length',
      MAX_LENGTH: 'Max Length',
      MAX_NAME_LENGTH: 'Max Name Length',
      MAX_OPTIONS: 'Max Options',
      MIN_CLIENT_LENGTH: 'Min Client Length',
      MIN_OPTIONS: 'Min Options',
      NAME_REQUIRED: 'Name Required',
      NOT_FOUND: 'Not Found',
      NOT_SINGLE_SELECTED: 'Not Single Selected',
      OPTION_NOT_FOUND: 'Option Not Found',
      QUESTION_MAX_LENGTH: 'Question Max Length',
      QUESTION_MIN_LENGTH: 'Question Min Length',
      QUESTION_NOT_FOUND: 'Question Not Found',
      QUESTION_REQUIRED: 'Question Required',
      QUESTION_REQUIRED_BEFORE_OPTION: 'Question Required Before Option',
      TARGET_AUDIENCE_MIN_MAX: 'Target Audience Min Max',
      TARGET_AUDIENCE_REQUIRED: 'Target Audience Required',
    },
    USER: {
      NOT_FOUND: 'Not Found',
    },
  },
  responseMessage: {
    EMAIL: {
      MAIL_SENT: 'Mail Sent successfully',
    },
    OTHER: {
      DATA_FOUND: 'Data Found successfully',
      DATA_NOT_FOUND: 'Data Not Found successfully',
    },
    SURVEY: {
      CREATED: 'Created successfully',
      DELETED: 'Deleted successfully',
      ENABLED: 'Enabled successfully',
      PUBLISHED: 'Published successfully',
      RESPONSE_RETRIEVED: 'Response Retrieved successfully',
      RETRIEVED: 'Retrieved successfully',
      SUBMITTED: 'Submitted successfully',
      UPDATED: 'Updated successfully',
      USER_NOT_SUBMITTED: 'User Not Submitted successfully',
      USER_SUBMITTED: 'User Submitted successfully',
    },
  },
  UserRoleEnum: {
    ADMIN: 'ADMIN',
    USER: 'USER',
  },
  ChartType: {
    MONTHLY: 'MONTHLY',
    WEEKLY: 'WEEKLY',
    YEARLY: 'YEARLY',
  },
  sendEmail: jest.fn(),
  utilFns: jest.fn(),
  utilFns: jest.fn(),
};
