# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: addtocart
# "service" is the name of this project. This will also be added to your AWS resource names.
service: atc-publish-widget

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: ap-south-1
  memorySize: 256 # Optional: Set memory for Lambda
  timeout: 30
  environment:
    DEV_DATABASE_URL: ${env:DEV_DATABASE_URL}

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: "*"

plugins:
  - serverless-offline
