module.exports = {
    displayName: 'API Gateway Service',
    preset: 'ts-jest',
    testEnvironment: 'node',
    rootDir: '.',
    testMatch: ['<rootDir>/__tests__/**/*.test.{ts,js}'],
    collectCoverageFrom: [
        'src/**/*.{ts,js}',
        '!src/**/*.d.ts',
        '!src/**/index.ts',
        '!src/**/*.interface.ts',
        '!src/**/*.type.ts',
        '!src/server.ts',
    ],
    coverageDirectory: '<rootDir>/coverage',
    coverageReporters: ['text', 'lcov', 'html'],
    setupFilesAfterEnv: ['<rootDir>/__tests__/setup.ts'],
    moduleNameMapper: {
        '^@atc/(.*)$': '<rootDir>/__tests__/__mocks__/@atc/$1',
        '^@/(.*)$': '<rootDir>/src/$1',
    },
    testTimeout: 10000,
    clearMocks: true,
    restoreMocks: true,
    resetMocks: true,
};
